#!/bin/bash

# ----------Install GO language -------------
# based on https://github.com/go-hep/binder/blob/master/postBuild
# and https://golang.org/dl/
# and what I had worked out in https://github.com/fomightez/gohugo-binder/blob/10659846159701870569312f169bd22542a851d1/postBuild

set -e

GOVERS=1.16.5

mkdir -p \
	$HOME/.local/go/$GOVERS \
	$HOME/.local/bin \
	$HOME/go

echo "::: install Go ${GOVERS}..."
curl -O -L https://golang.org/dl/go${GOVERS}.linux-amd64.tar.gz
tar -C $HOME/.local/go/$GOVERS -zxf go${GOVERS}.linux-amd64.tar.gz
/bin/rm go${GOVERS}.linux-amd64.tar.gz

export GOROOT=$HOME/.local/go/$GOVERS/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
echo $GOPATH
# add it to path like in https://github.com/aborruso/bashnotebook/blob/0de5d657de745fffe53ed1acc35d01c75d389b6e/binder/postBuild#L48
cd ~/.local/bin
ln -s $GOROOT/bin/go go
cd ~


# ----------Install pixterm -------------
# based on https://github.com/eliukblau/pixterm#installation
# and what is necessary to add it to path
go get -u github.com/eliukblau/pixterm/cmd/pixterm
# add it to path like in https://github.com/aborruso/bashnotebook/blob/0de5d657de745fffe53ed1acc35d01c75d389b6e/binder/postBuild#L48
cd ~/.local/bin
ln -s ~/go/bin/pixterm pixterm
cd ~
